language: java

jdk:
  - oraclejdk8

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
- mvn test

deploy:
  skip_cleanup: true
  file: "rombonganbelajar_microservices.jar"
  on: RombonganBelajar-Microservices-Server